# Generated by Django 5.1.7 on 2025-04-02 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_remove_cameraconfiguration_success_sound_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_class',
            new_name='department',
        ),
    ]
