# Generated by Django 5.1.7 on 2025-04-04 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_rename_name_student_username_alter_student_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='username',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='password',
        ),
    ]
