# Generated by Django 5.1.7 on 2025-04-06 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_rename_username_student_name_remove_student_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='check_in_time',
            new_name='check_in_1',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='check_out_time',
            new_name='check_out_1',
        ),
    ]
