# Generated by Django 5.1.7 on 2025-04-07 04:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_attendance_check_in_2_attendance_check_in_3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='total_monthly_duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
